InrappAdmin.Web/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.WebPages;
using InrappAdmin.ApplicationService;
using InrappAdmin.ApplicationService.Interface;
using InrappAdmin.DataAccess;
using InrappAdmin.DomainModel;
using InrappAdmin.Web.Helpers;
using InrappAdmin.Web.Models;
using InrappAdmin.Web.Models.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;

namespace InrappAdmin.Web.Controllers
{
    public class AdminController : Controller
    {
        private readonly IPortalAdminService _portalAdminService;
        private ApplicationUserManager _userManager;

        public AdminController(ApplicationUserManager userManager)
        {
            UserManager = userManager;
            _portalAdminService =
                new PortalAdminService(new PortalAdminRepository(new InrappAdminDbContext(), new InrappAdminIdentityDbContext()));
        }

        public AdminController()
        {
            _portalAdminService =
                new PortalAdminService(new PortalAdminRepository(new InrappAdminDbContext(), new InrappAdminIdentityDbContext()));
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }


        // GET: Astrid users
        [Authorize]
        public ActionResult GetAstridUsers()
        {
            var model = new AdminViewModels.AdminViewModel();
            
            try
            {
                var adminUsers = _portalAdminService.HamtaAdminUsers();
                model.AdminUsers = ConvertAdminUsersToViewModel(adminUsers);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                ErrorManager.WriteToErrorLog("AdminController", "GetAstridUsers", e.ToString(), e.HResult, User.Identity.Name);
                var errorModel = new CustomErrorPageModel
                {
                    Information = "Ett fel inträffade vid hämtning av admin-användare",
                    ContactEmail = ConfigurationManager.AppSettings["ContactEmail"],
                };
                return View("CustomError", errorModel);

            }
            return View("Index", model);
        }

        [HttpPost]
        [Authorize]
        public ActionResult UpdateAdminUser(AdminViewModels.AppUserAdminViewModel user)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var userName = User.Identity.GetUserName();
                    var userToUpdate = ConvertViewModelToAppUserAdmin(user);
                    _portalAdminService.UppdateraAdminAnvandare(userToUpdate, userName);
                }
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                ErrorManager.WriteToErrorLog("AdminController", "UpdateAdminUser", e.ToString(), e.HResult,
                    User.Identity.Name);
                var errorModel = new CustomErrorPageModel
                {
                    Information = "Ett fel inträffade vid uppdatering av Astrid-användare.",
                    ContactEmail = ConfigurationManager.AppSettings["ContactEmail"],
                };
                return View("CustomError", errorModel);
            }
            return RedirectToAction("GetAstridUsers");

        }

        [HttpPost]
        [Authorize]
        public ActionResult DeleteAdminUser(string userId)
        {
            try
            {
                _portalAdminService.TaBortAdminAnvandare(userId);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                ErrorManager.WriteToErrorLog("AdminController", "DeleteAdminUser", e.ToString(), e.HResult, User.Identity.Name);
                var errorModel = new CustomErrorPageModel
                {
                    Information = "Ett fel inträffade när Astrid-användare skulle tas bort.",
                    ContactEmail = ConfigurationManager.AppSettings["ContactEmail"],
                };
                return View("CustomError", errorModel);
            }
            return RedirectToAction("GetAstridUsers");
        }

        private IEnumerable<AdminViewModels.AppUserAdminViewModel> ConvertAdminUsersToViewModel(IEnumerable<AppUserAdmin> adminUsers)
        {
            var adminUserViewList = new List<AdminViewModels.AppUserAdminViewModel>();

            foreach (var user in adminUsers)
            {
                var adminUserView = new AdminViewModels.AppUserAdminViewModel
                {
                    Id = user.Id,
                    Email = user.Email,
                    PhoneNumber = user.PhoneNumber,
                    SkapadDatum = user.SkapadDatum,
                    SkapadAv = user.SkapadAv,
                    AndradDatum = user.AndradDatum,
                    AndradAv = user.AndradAv,
                    Roles = UserManager.GetRoles(user.Id)
                };
                var rolesStr = String.Empty;


                //TODO - Gör lista av roller till sträng tills vidare
                //for (int i = 0; i < adminUserView.Roles.Count; i++)
                //{
                //    //Om första eller sista i listan
                //    if (rolesStr.IsEmpty() || (i++ == adminUserView.Roles.Count))
                //    {
                //        rolesStr = rolesStr + adminUserView.Roles[i];
                //    }
                //    else
                //    {
                //        rolesStr = rolesStr + "," + adminUserView.Roles[i];
                //    }
                //}


                foreach (var role in adminUserView.Roles)
                {
                    if (rolesStr.IsEmpty())
                    {
                        rolesStr = role;
                    }
                    else
                    {
                        rolesStr = rolesStr + ","  + role;
                    }
                    
                }

                adminUserView.StringOfRoles = rolesStr;
                adminUserViewList.Add(adminUserView);
            }
            return adminUserViewList;


        }

        private AppUserAdmin ConvertViewModelToAppUserAdmin(AdminViewModels.AppUserAdminViewModel adminUserVM)
        {
            var user = new AppUserAdmin()
            {
                Id = adminUserVM.Id,
                Email = adminUserVM.Email,
                PhoneNumber = adminUserVM.PhoneNumber
            };

            return user;
        }
    }
}

InrappAdmin.Web/Controllers/SystemController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.WebPages;
using InrappAdmin.ApplicationService;
using InrappAdmin.ApplicationService.DTOModel;
using InrappAdmin.ApplicationService.Interface;
using InrappAdmin.DataAccess;
using InrappAdmin.DomainModel;
using InrappAdmin.Web.Helpers;
using InrappAdmin.Web.Models;
using InrappAdmin.Web.Models.ViewModels;
using Microsoft.AspNet.Identity;

namespace InrappAdmin.Web.Controllers
{
    public class SystemController : Controller
    {
        private readonly IPortalAdminService _portalAdminService;

        public SystemController()
        {
            _portalAdminService =
                new PortalAdminService(new PortalAdminRepository(new InrappAdminDbContext(), new InrappAdminIdentityDbContext()));
        }

        // GET: System
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }

        // GET: FAQCategories
        [Authorize]
        public ActionResult GetFAQCategories()
        {
            var model = new SystemViewModels.SystemViewModel();
            try
            {
                model.FAQCategories = _portalAdminService.HamtaFAQkategorier();
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                ErrorManager.WriteToErrorLog("SystemController", "GetFAQCategories", e.ToString(), e.HResult, User.Identity.Name);
                var errorModel = new CustomErrorPageModel
                {
                    Information = "Ett fel inträffade vid hämtning av FAQ-kategorier",
                    ContactEmail = ConfigurationManager.AppSettings["ContactEmail"],
                };
                return View("CustomError", errorModel);

            }
            return View("EditFAQCategory", model);
        }


        // GET: FAQs
        [Authorize]
        public ActionResult GetFAQs(int faqCatId = 0, string faqCatName = "")
        {
            var model = new SystemViewModels.SystemViewModel();
            try
            {
                var faqs = _portalAdminService.HamtaFAQs(faqCatId);
                model.FAQs = ConvertAdmFAQToViewModel(faqs.ToList());
                model.SelectedFAQCategory = faqCatId;
                if (faqCatId != 0 && faqCatName.IsEmpty())
                {
                    var faqCat = _portalAdminService.HamtaFAQKategori(faqCatId);
                    model.SelectedFAQCategoryName = faqCat.Kategori;
                }
                else
                {
                    model.SelectedFAQCategoryName = faqCatName;
                }
                
                // Ladda drop down lists. 
                var registerList = _portalAdminService.HamtaAllaRegisterForPortalen();
                this.ViewBag.RegisterList = CreateRegisterDropDownList(registerList);
                //model.SelectedFAQ.SelectedRegisterId = 0;
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                ErrorManager.WriteToErrorLog("SystemController", "GetFAQs", e.ToString(), e.HResult, User.Identity.Name);
                var errorModel = new CustomErrorPageModel
                {
                    Information = "Ett fel inträffade vid hämtning av FAQs",
                    ContactEmail = ConfigurationManager.AppSettings["ContactEmail"],
                };
                return View("CustomError", errorModel);

            }
            return View("EditFAQs", model);
        }


        // GET: InformationTexts
        [Authorize]
        [ValidateInput(false)]
        public ActionResult GetInformationTexts(string selectedInfoType = "", string selectedText = "")
        {
            var model = new SystemViewModels.SystemViewModel();
            try
            {
                model.InfoPages = _portalAdminService.HamtaInformationstexter();
                model.SelectedInfo = selectedInfoType;
                model.SelectedInfoText = selectedText;
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                ErrorManager.WriteToErrorLog("SystemController", "GetInformationTexts", e.ToString(), e.HResult, User.Identity.Name);
                var errorModel = new CustomErrorPageModel
                {
                    Information = "Ett fel inträffade vid hämtning av informationstexter.",
                    ContactEmail = ConfigurationManager.AppSettings["ContactEmail"],
                };
                return View("CustomError", errorModel);

            }
            return View("EditInfoTexts", model);
        }


        // GET: OpeningHours (AdmKonfiguration)
        [Authorize]
        public ActionResult GetOpeningHours()
        {
            var model = new SystemViewModels.OpeningHours();
            try
            {
                var admKonf = _portalAdminService.HamtaOppettider();
                model.ClosedAnyway = admKonf.ClosedAnyway;
                model.ClosedDaysList = _portalAdminService.MarkeraStangdaDagar(admKonf.ClosedDays);
                //model.OpeningTime = SetTime(admKonf.ClosedToHour, admKonf.ClosedToMin);
                //model.ClosingTime = SetTime(admKonf.ClosedFromHour, admKonf.ClosedFromMin);
                DateTime s = DateTime.MinValue;
                TimeSpan ts = new TimeSpan(10, 30, 0);
                model.OpeningTime = s.Date + ts;
                model.OpeningTimeStr = admKonf.ClosedToHour.ToString() + ":" + admKonf.ClosedToMin.ToString();
                //model.ClosingTime = SetTime(admKonf.ClosedFromHour, admKonf.ClosedFromMin);
                model.ClosingTimeStr = admKonf.ClosedFromHour.ToString() + ":" + admKonf.ClosedFromMin.ToString();
                model.InfoTextForClosedPage = _portalAdminService.HamtaInfoText("Stangtsida").Text;
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                ErrorManager.WriteToErrorLog("SystemController", "GetOpeningHours", e.ToString(), e.HResult, User.Identity.Name);
                var errorModel = new CustomErrorPageModel
                {
                    Information = "Ett fel inträffade vid hämtning av öppettider.",
                    ContactEmail = ConfigurationManager.AppSettings["ContactEmail"],
                };
                return View("CustomError", errorModel);

            }
            return View("EditOpeningHours", model);
        }


        // GET: Helgdagar
        [Authorize]
        public ActionResult GetHolidays()
        {
            var model = new SystemViewModels.SystemViewModel();
            try
            {
                var holidayList = _portalAdminService.HamtaAllaHelgdagar();
                model.Holidays = ConvertAdmHelgdagToViewModel(holidayList.ToList());
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                ErrorManager.WriteToErrorLog("SystemController", "GetHolidays", e.ToString(), e.HResult, User.Identity.Name);
                var errorModel = new CustomErrorPageModel
                {
                    Information = "Ett fel inträffade vid hämtning av helgdagar.",
                    ContactEmail = ConfigurationManager.AppSettings["ContactEmail"],
                };
                return View("CustomError", errorModel);

            }
            return View("EditHolidays", model);
        }

        // GET: Specialdagar
        [Authorize]
        public ActionResult GetSpecialDays()
        {
            var model = new SystemViewModels.SystemViewModel();
            try
            {
                var specialdaysList = _portalAdminService.HamtaAllaSpecialdagar();
                model.SpecialDays = ConvertAdmSpecialdagToViewModel(specialdaysList.ToList());
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                ErrorManager.WriteToErrorLog("SystemController", "GetSpecialDays", e.ToString(), e.HResult, User.Identity.Name);
                var errorModel = new CustomErrorPageModel
                {
                    Information = "Ett fel inträffade vid hämtning av specialdagar.",
                    ContactEmail = ConfigurationManager.AppSettings["ContactEmail"],
                };
                return View("CustomError", errorModel);

            }
            return View("EditSpecialDays", model);
        }

        [HttpPost]
        [Authorize]
        public ActionResult UpdateFAQCategory(AdmFAQKategori faqCategory)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var userName = User.Identity.GetUserName();
                    _portalAdminService.UppdateraFAQKategori(faqCategory, userName);
                }
                catch (Exception e)
                {
                    Console.WriteLine(e);
                    ErrorManager.WriteToErrorLog("SystemController", "UpdateFAQCategory", e.ToString(), e.HResult,
                        User.Identity.Name);
                    var errorModel = new CustomErrorPageModel
                    {
                        Information = "Ett fel inträffade vid uppdatering av FAQ-kategori.",
                        ContactEmail = ConfigurationManager.AppSettings["ContactEmail"],
                    };
                    return View("CustomError", errorModel);

                }
            }
            return RedirectToAction("GetFAQCategories");
        }

        [HttpPost]
        [Authorize]
        public ActionResult UpdateFAQ(SystemViewModels.SystemViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var userName = User.Identity.GetUserName();
                    var faqDb = ConvertViewModelToAdmFAQ(model.SelectedFAQ);

InrappAdmin.Web/Views/Shared/CustomError.cshtml
@model InrappAdmin.Web.Models.CustomErrorPageModel

@{
    ViewBag.Title = "Ett fel inträffade";
}

<br /><br />
<div>
    <H2 class="text-danger">@Model.Information</H2>
    <br />
    För mer information kontakta support.
    <br/>
    <address>
        <strong>Support, epost:</strong> <a href="mailto:inrapportering@socialstyrelsen.se">@Model.ContactEmail</a><br />
    </address>
</div>

InrappAdmin.Web/Views/Shared/FileNotFound.cshtml
@model System.Web.Mvc.HandleErrorInfo

@{
    ViewBag.Title = "Ett oväntat fel inträffade";
}

<br /><br />
<div>
    <H2 class="text-danger">Oväntat fel</H2>
    <br />
    Filen kunde inte hittas.
    För mer information kontakta support.
    <br />
    <address>
        <strong>Support, epost:</strong> <a href="mailto:inrapportering@socialstyrelsen.se">inrapportering@socialstyrelsen.se </a><br />
    </address>
</div>

InrappAdmin.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ASTRID</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
</head>
<body>
@Html.Action("Menu", "Navigation")

    <div class="container body-content">
        @RenderBody()
        <hr />
        <div id="footer">
            <footer>
                <p>&copy; @DateTime.Now.Year - Administrationsgränssnitt för Socialstyrelsens InrappAdmin</p>
            </footer>            
        </div>

    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

InrappAdmin.Web/Views/Shared/_LayoutUtv.cshtml
@using System.Configuration
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ASTRID</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    
    <link href="@Url.Content("~/Content/NavBarDev.css")" rel="stylesheet" type="text/css"/>

</head>
<body>
@Html.Action("Menu", "Navigation")

    <div class="container body-content">
        @RenderBody()
        <hr />
        <div id="footer">
            <footer>
                <p>&copy; @DateTime.Now.Year - Administrationsgränssnitt för Socialstyrelsens InrappAdmin</p>
            </footer>            
        </div>

    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

InrappAdmin.Web/Views/Shared/_LoginAdmin.cshtml
@using Microsoft.Ajax.Utilities

<script>
    (function($){
        $(document).ready(function(){
            $('ul.dropdown-menu [data-toggle=dropdown]').on('click', function(event) {
                event.preventDefault();
                event.stopPropagation();
                $(this).parent().siblings().removeClass('open');
                $(this).parent().toggleClass('open');
            });
        });
    })(jQuery);
</script>

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" rel="home" href='@Url.Action("Index", "Home")' title="Socialstyrelsen">
                <img src="~/Content/Images/LoggaNew200px.PNG">
            </a>
            @Html.ActionLink("Astrid", "Index", "Home", new { area = "" }, new { @class = "navbar-brand", style = "margin-top: 17px; font-size:2em;padding-left:30px;" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav" style="margin-top: 20px">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">System <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink("FAQ", "GetFAQCategories", "System")</li>
                        <li>@Html.ActionLink("Informationssidor", "GetInformationTexts", "System")</li>
                        <li class="dropdown dropdown-submenu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Öppettider</a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Ordinarie öppettider", "GetOpeningHours", "System")</li>
                                <li>@Html.ActionLink("Helgdagar", "GetHolidays", "System")</li>
                                <li>@Html.ActionLink("Specialdagar", "GetSpecialDays", "System")</li>
                            </ul>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Register och delregister <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink("Register", "Index", "Register")</li>
                        <li>@Html.ActionLink("Delregister", "GetAllSubDirectories", "Register")</li>
                    </ul>
                </li>

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Organisation <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink("Organisation", "Index", "Organisation")</li>
                        <li>@Html.ActionLink("Skapa ny organisation", "CreateOrganisation", "Organisation")</li>
                        <li>@Html.ActionLink("Kontaktpersoner", "GetContacts", "Organisation")</li>
                        <li>@Html.ActionLink("Organisationsenheter", "GetOrgUnits", "Organisation")</li>
                        <li>@Html.ActionLink("Uppgiftsskyldighet", "GetReportObligations", "Organisation")</li>
                        <li>@Html.ActionLink("Enhetsuppgiftsskyldighet", "GetUnitReportObligations", "Organisation")</li>
                        @*<li><a href="#">Something else here</a></li>
        <li role="separator" class="divider"></li>
        <li><a href="#">Separated link</a></li>
        <li role="separator" class="divider"></li>
        <li><a href="#">One more separated link</a></li>*@
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Leverans <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink("Insamlingsfrekvenser", "GetInsamlingsfrekvens", "Leverans")</li>
                        <li>@Html.ActionLink("Filkrav", "GetFilkrav", "Leverans")</li>
                        <li>@Html.ActionLink("Förväntad leverans", "Index", "Leverans")</li>
                        <li>@Html.ActionLink("Förväntad fil", "GetForvantadeFiler", "Leverans")</li>
                        <li class="dropdown dropdown-submenu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Leveranser</a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Leveranshistorik", "GetDeliveries", "Leverans")</li>
                                <li>@Html.ActionLink("Leveransstatus per organisation", "GetDeliveryStatus", "Leverans")</li>
                            </ul>
                        </li>
                        <li>@Html.ActionLink("Påminnelser", "GetReminderinfo", "Leverans")</li>
                    </ul>
                </li>
            @if (Request.IsAuthenticated)
            {
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink("Användare", "GetAstridUsers", "Admin")</li>
                        <li>@Html.ActionLink("Reg anv", "Register", "Account", routeValues: null, htmlAttributes: new {id = "registerLink"})</li>
                    </ul>
                </li>
            }

            </ul>
            @if (Request.IsAuthenticated)
            {
                using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new {id = "logoutForm", @class = "navbar-right"}))
                {
                    @Html.AntiForgeryToken()
                    <ul class="nav navbar-nav navbar-right" style="margin-top: 20px">
                        @*<li>@Html.ActionLink("Reg anv", "Register", "Account", routeValues: null, htmlAttributes: new {id = "registerLink"})</li>*@
                        <li>@Html.ActionLink("Min sida", "Index", "Manage", routeValues: null, htmlAttributes: new {title = "Manage"})</li>
                        <li><a href="javascript:document.getElementById('logoutForm').submit()">Logga ut</a></li>
                    </ul>
                }
            }
            else
            {
                <ul class="nav navbar-nav navbar-right" style="margin-top: 20px">
                    <li>@Html.ActionLink("Logga in", "Login", "Account", routeValues: null, htmlAttributes: new {id = "loginLink"})</li>
                </ul>
            }
        </div>
    </div>
</div>