InrappAdmin.Web/Models/ViewModels/LeveransViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using InrappAdmin.ApplicationService.DTOModel;
using InrappAdmin.DomainModel;

namespace InrappAdmin.Web.Models.ViewModels
{
    public class LeveransViewModels
    {
        public class LeveransViewModel
        {
            public IEnumerable<RegisterInfo> RegisterList { get; set; }
            public IEnumerable<AdmForvantadleveransViewModel> ForvantadeLeveranser { get; set; }

            public List<AdmForvantadleveransViewModel> BlivandeForvantadeLeveranser { get; set; }
            public IEnumerable<AdmForvantadfilViewModel> ForvantadeFiler { get; set; }
            public List<AdmFilkravViewModel> Filkrav { get; set; }
            public IEnumerable<FilloggDetaljDTO> Leveranser { get; set; }
            public IEnumerable<AdmInsamlingsfrekvens> Insamlingsfrekvenser { get; set; }
            public int SelectedRegisterId { get; set; }
            public int SelectedOrganisationId { get; set; }
            public int SelectedDelregisterId { get; set; }
            public int SelectedFilkravId { get; set; }
            public int SelectedInsamlingsfrekvensId { get; set; }
            [DisplayName("Visa endast pågående")]
            public bool FilterPagaende{ get; set; }
            [Display(Name = "År")]
            public int SelectedYear { get; set; }
            public string SelectedCountyCode { get; set; }
            [Display(Name = "Kommunkod")]
            public string Kommunkod { get; set; }

            public AdmInsamlingsfrekvens Insamlingsfrekvens { get; set; }

        }

        public class AdmForvantadleveransViewModel
        {
            public int Id { get; set; }
            public int FilkravId { get; set; }
            public string FilkravNamn { get; set; }
            public int DelregisterId { get; set; }
            public int SelectedDelregisterId { get; set; }
            public int SelectedRegisterId { get; set; }
            public int SelectedFilkravId { get; set; }

            public string DelregisterKortnamn { get; set; }
            public IEnumerable<RegisterInfo> RegisterList { get; set; }
            public IEnumerable<FilloggDetaljDTO> Leveranser { get; set; }
            public string Period { get; set; }
            [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
            public DateTime Uppgiftsstart { get; set; }
            [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
            public DateTime Uppgiftsslut { get; set; }
            [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
            public DateTime Rapporteringsstart { get; set; }
            [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
            public DateTime Rapporteringsslut { get; set; }
            [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
            public DateTime Rapporteringsenast { get; set; }
            public DateTime? Paminnelse1 { get; set; }
            public DateTime? Paminnelse2 { get; set; }
            public DateTime? Paminnelse3 { get; set; }
            public bool Pagaende { get; set; }
            public bool Sen { get; set; }
            public bool AlreadyExists { get; set; }
        }

        public class AdmForvantadfilViewModel
        {
            public int Id { get; set; }
            public IEnumerable<RegisterInfo> RegisterList { get; set; }
            public int SelectedDelregisterId { get; set; }
            public int SelectedRegisterId { get; set; }
            public int SelectedFilkravId { get; set; }
            public int FilkravId { get; set; }
            public string FilkravNamn { get; set; }
            public int? ForeskriftsId { get; set; }
            public string DelregisterKortnamn { get; set; }
            [Required(ErrorMessage = "Fältet Filmask är obligatoriskt.")]
            public string Filmask { get; set; }
            [Required(ErrorMessage = "Fältet Regexp är obligatoriskt.")]
            public string Regexp { get; set; }
            public bool Obligatorisk { get; set; }
            public bool Tom { get; set; }
        }

        public class AdmFilkravViewModel
        {
            public int Id { get; set; }
            public int DelregisterId { get; set; }
            public int SelectedDelregisterId { get; set; }
            public int SelectedRegisterId { get; set; }
            public string DelregisterKortnamn { get; set; }
            public int? InsamlingsfrekvensId { get; set; }
            public SelectList InsamlingsfrekvensDDL { get; set; }
            public string Insamlingsfrekvens { get; set; }
            public int? ForeskriftsId { get; set; }
            public string Namn { get; set; }
            public int? Uppgiftsstartdag { get; set; }
            public int? Uppgiftslutdag { get; set; }
            public int? Rapporteringsstartdag { get; set; }
            public int? Rapporteringsslutdag { get; set; }
            [Display(Name = "Rapportering senast dag")]
            public int? RapporteringSenastdag { get; set; }
            [Display(Name = "Påminnelse 1")]
            public int? Paminnelse1dag { get; set; }
            [Display(Name = "Påminnelse 2")]
            public int? Paminnelse2dag { get; set; }
            [Display(Name = "Påminnelse 3")]
            public int? Paminnelse3dag { get; set; }
            [Display(Name = "Rapportering efter antal månader")]
            public int? RapporteringEfterAntalManader { get; set; }
            [Display(Name = "Uppgifter antal manader")]
            public int? UppgifterAntalmanader { get; set; }

        }

        public class ReminderViewModel
        {
            public int SelectedRegisterId { get; set; }
            public int SelectedDelregisterId { get; set; }
            public string SelectedPeriod { get; set; }

            public IEnumerable<RegisterBasicDTO> RegisterList { get; set; }

            public List<RapporteringsresultatDTO> RapportResList { get; set; }
            public int AntRader { get; set; }
        }


        public class HistoryViewModel
        {
            public string Kommunkod { get; set; }
            public int SelectedOrganisationId { get; set; }
            public string OrganisationsNamn { get; set; }
            public List<FilloggDetaljDTO> HistorikLista { get; set; }
            public List<AdmRegisterViewModel> RegisterList { get; set; }
            public List<RegisterLeveransDTO> LeveransListaRegister { get; set; }

            public int SelectedYear { get; set; }
            public List<int> SelectableYears { get; set; }

        }

        public class AdmRegisterViewModel
        {
            public int Id { get; set; }
            public string Registernamn { get; set; }
            public string Beskrivning { get; set; }
            public string Kortnamn { get; set; }

            public IEnumerable<AdmDelregisterViewModel> DelRegister { get; set; }
        }

        public class AdmDelregisterViewModel
        {
            public int Id { get; set; }
            public int RegisterId { get; set; }
            public string Delregisternamn { get; set; }
            public string Kortnamn { get; set; }
            public string Beskrivning { get; set; }
        }
    }
}

InrappAdmin.Web/Controllers/LeveransController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net.Configuration;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using InrappAdmin.ApplicationService;
using InrappAdmin.ApplicationService.DTOModel;
using InrappAdmin.ApplicationService.Interface;
using InrappAdmin.DataAccess;
using InrappAdmin.DomainModel;
using InrappAdmin.Web.Helpers;
using InrappAdmin.Web.Models;
using InrappAdmin.Web.Models.ViewModels;
using Microsoft.Ajax.Utilities;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security.Provider;

namespace InrappAdmin.Web.Controllers
{
    public class LeveransController : Controller
    {

        private readonly IPortalAdminService _portalAdminService;

        public LeveransController()
        {
            _portalAdminService =
                new PortalAdminService(new PortalAdminRepository(new InrappAdminDbContext(), new InrappAdminIdentityDbContext()));
        }

        [Authorize]
        // GET: Leverans
        public ActionResult Index(bool filterPgnde = false, int regId = 0)
        {

            var model = new LeveransViewModels.LeveransViewModel();
            try
            {
                var tmpPagaende = Request.QueryString["filterPagaende"];
                var filterPagaende = false;

                if (tmpPagaende != null)
                {
                    Char delimiter = ',';
                    String[] substrings = tmpPagaende.Split(delimiter);
                    filterPagaende = Convert.ToBoolean(substrings.Last());
                }
                else
                {
                    filterPagaende = filterPgnde;
                }
                var forvLevList = _portalAdminService.HamtaForvantadeLeveranser();
                model.ForvantadeLeveranser = ConvertForvLevToViewModel(forvLevList.ToList());
                // Ladda drop down lists. 
                var registerList = _portalAdminService.HamtaAllaRegisterForPortalen();
                this.ViewBag.RegisterList = CreateRegisterDropDownList(registerList);
                model.SelectedRegisterId = regId;
                model.FilterPagaende = filterPagaende;

            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                ErrorManager.WriteToErrorLog("LeveransController", "Index", e.ToString(), e.HResult, User.Identity.Name);
                var errorModel = new CustomErrorPageModel
                {
                    Information = "Ett fel inträffade vid hämtning av förväntade leveranser",
                    ContactEmail = ConfigurationManager.AppSettings["ContactEmail"],
                };
                return View("CustomError", errorModel);

            }
            return View("Index", model);
        }

        // GET
        [Authorize]
        public ActionResult GetDirectorysExpectedDeliveries(LeveransViewModels.LeveransViewModel model, bool filterPgnde = false, int regId = 0)
        {
            try
            {
                var tmpPagaende = Request.QueryString["filterPagaende"];
                var filterPagaende = false;

                if (tmpPagaende != null)
                {
                    Char delimiter = ',';
                    String[] substrings = tmpPagaende.Split(delimiter);
                    filterPagaende = Convert.ToBoolean(substrings.Last());
                }
                else if (filterPgnde)
                {
                    filterPagaende = filterPgnde;
                }
                else
                {
                    filterPagaende = model.FilterPagaende;
                }
                var dirId = model.SelectedRegisterId;
                if (dirId == 0 && regId != 0)
                {
                    dirId = regId;
                }
                if (dirId != 0)
                {
                    var forvLevList = _portalAdminService.HamtaForvantadeLeveranserForRegister(dirId);
                    //Lägg över i modellen
                    model.ForvantadeLeveranser = ConvertForvLevToViewModel(forvLevList.ToList());
                    // Ladda drop down lists. 
                    var registerList = _portalAdminService.HamtaAllaRegisterForPortalen();
                    this.ViewBag.RegisterList = CreateRegisterDropDownList(registerList);
                    model.SelectedRegisterId = dirId;
                    model.FilterPagaende = filterPagaende;
                }
                else
                {
                    return RedirectToAction("Index", new { filterPgnde = filterPagaende });
                }
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                ErrorManager.WriteToErrorLog("LeveransController", "GetDirectorysExpectedDeliveries", e.ToString(), e.HResult, User.Identity.Name);
                var errorModel = new CustomErrorPageModel
                {
                    Information = "Ett fel inträffade vid hämtning av förväntade leveranser för register",
                    ContactEmail = ConfigurationManager.AppSettings["ContactEmail"],
                };
                return View("CustomError", errorModel);

            }
            return View("Index", model);
        }

        // GET
        [Authorize]
        public ActionResult GetDirectorysExpectedFiles(LeveransViewModels.LeveransViewModel model, int regId = 0)
        {
            try
            {
                var dirId = model.SelectedRegisterId;
                if (dirId == 0 && regId != 0)
                {
                    dirId = regId;
                }
                if (dirId != 0)
                {
                    var register = _portalAdminService.HamtaRegisterMedId(dirId);
                    var forvFilList = _portalAdminService.HamtaForvantadeFilerForRegister(register.Id);
                    //Lägg över i modellen
                    model.ForvantadeFiler = ConvertForvFilToViewModel(forvFilList.ToList());
                    // Ladda drop down lists. 
                    var registerList = _portalAdminService.HamtaAllaRegisterForPortalen();
                    this.ViewBag.RegisterList = CreateRegisterDropDownList(registerList);
                    model.SelectedRegisterId = dirId;
                }
                else
                {
                    return RedirectToAction("GetForvantadeFiler");
                }
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                ErrorManager.WriteToErrorLog("LeveransController", "GetDirectorysExpectedFiles", e.ToString(), e.HResult, User.Identity.Name);
                var errorModel = new CustomErrorPageModel
                {
                    Information = "Ett fel inträffade vid hämtning av förväntade filer för register",
                    ContactEmail = ConfigurationManager.AppSettings["ContactEmail"],
                };
                return View("CustomError", errorModel);
            }
            return View("EditForvantadFil", model);
        }

        // GET
        [Authorize]
        public ActionResult GetDirectorysFilerequirements(LeveransViewModels.LeveransViewModel model, int regId = 0)
        {
            try
            {
                var dirId = model.SelectedRegisterId;
                if (dirId == 0 && regId != 0)
                {
                    dirId = regId;
                }
                if (dirId != 0)
                {
                    var register = _portalAdminService.HamtaRegisterMedId(dirId);
                    var filkravList = _portalAdminService.HamtaFilkravForRegister(register.Id);
                    //Lägg över i modellen
                    model.Filkrav = ConvertFilkravToViewModel(filkravList.ToList());
                    // Ladda drop down lists. 
                    var registerList = _portalAdminService.HamtaAllaRegisterForPortalen();
                    this.ViewBag.RegisterList = CreateRegisterDropDownList(registerList);
                    model.SelectedRegisterId = dirId;
                    var insamlingsfrekvensList = _portalAdminService.HamtaAllaInsamlingsfrekvenser();
                    ViewBag.InsamlingsfrekvensList = CreateInsamlingsfrekvensDropDownList(insamlingsfrekvensList);
                    model.SelectedInsamlingsfrekvensId = 0;
                }
                else
                {
                    return RedirectToAction("GetFilkrav");
                }
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                ErrorManager.WriteToErrorLog("LeveransController", "GetDirectorysFilerequirements", e.ToString(), e.HResult, User.Identity.Name);
                var errorModel = new CustomErrorPageModel
                {
                    Information = "Ett fel inträffade vid hämtning av filkrav för register",
                    ContactEmail = ConfigurationManager.AppSettings["ContactEmail"],
                };
                return View("CustomError", errorModel);
            }
            return View("EditFilkrav", model);
        }

        

        // GET: AdmForvantadfil
        [Authorize]
        public ActionResult GetForvantadeFiler()
        {
            var model = new LeveransViewModels.LeveransViewModel();
            try
            {
                var forvFilViewList = new List<LeveransViewModels.AdmForvantadfilViewModel>();
                var forvFiler = _portalAdminService.HamtaAllaForvantadeFiler();

                foreach (var forvFil in forvFiler)
                {
                    var forvFilView = new LeveransViewModels.AdmForvantadfilViewModel
                        {
                          Id  = forvFil.Id,
                          FilkravId = forvFil.FilkravId,
                          FilkravNamn = _portalAdminService.HamtaNamnForFilkrav(forvFil.FilkravId),

InrappAdmin.Web/Views/Leverans/CreateFilkrav.cshtml
@model InrappAdmin.Web.Models.ViewModels.LeveransViewModels.AdmFilkravViewModel

@{
    ViewBag.Title = "Skapa nytt filkrav";
}

<script type="text/javascript">
    $(document).on('change', '#ddlDelregister', function () {
        $("#SelectedDelregisterId").val($('#ddlDelregister').val());
    });

    $(document).on('change', '#ddlInsamlingsfrekvens', function () {
        $("#SelectedInsamlingsfrekvensId").val($('#ddlInsamlingsfrekvens').val());
    });

</script>


    @using (Html.BeginForm("CreateFilkrav", "Leverans", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal padding-top-55">
            <h4>Skapa filkrav</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            
            <div class="form-group">
                @Html.LabelFor(model => model.ForeskriftsId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ForeskriftsId, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ForeskriftsId, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.Label("Delregister", new { @class = "control-label col-md-2" })
                @*@Html.LabelFor(model => model.DelregisterId, htmlAttributes: new {@class = "control-label col-md-2"})*@
                <div class="col-md-10" style="width: 255px !important;">
                    @Html.DropDownListFor(m => m.SelectedDelregisterId, ViewBag.DelregisterList as SelectList, " - Välj delregister -", new {id = "ddlDelregister", @class = "form-control", style = "max-width:250px !important"})
                </div>
            </div>
            
            <div class="form-group">
                @Html.LabelFor(model => model.Namn, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Namn, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Namn, "", new { @class = "text-danger" })
                </div>
            </div>
            
            <div class="form-group">
                @Html.Label("Insamlingsfrekvens", new { @class = "control-label col-md-2" })
                <div class="col-md-10" style="width: 255px !important;">
                    @Html.DropDownListFor(m => m.InsamlingsfrekvensId, ViewBag.InsamlingsfrekvensList as SelectList, " - Välj insamlingsfrekvens -", new {id = "ddlInsamlingsfrekvens", @class = "form-control", style = "max-width:250px !important"})
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Uppgiftsstartdag, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Uppgiftsstartdag, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Uppgiftsstartdag, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Uppgiftslutdag, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Uppgiftslutdag, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Uppgiftslutdag, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Rapporteringsstartdag, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Rapporteringsstartdag, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Rapporteringsstartdag, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Rapporteringsslutdag, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Rapporteringsslutdag, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Rapporteringsslutdag, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.RapporteringSenastdag, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.RapporteringSenastdag, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.RapporteringSenastdag, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Paminnelse1dag, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Paminnelse1dag, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Paminnelse1dag, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Paminnelse2dag, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Paminnelse2dag, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Paminnelse2dag, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Paminnelse3dag, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Paminnelse3dag, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Paminnelse3dag, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.RapporteringEfterAntalManader, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.RapporteringEfterAntalManader, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.RapporteringEfterAntalManader, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.UppgifterAntalmanader, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.UppgifterAntalmanader, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.UppgifterAntalmanader, "", new { @class = "text-danger" })
                </div>
            </div>

            
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Spara" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Tillbaka", "GetDirectorysFilerequirements", "Leverans", new { regId = Model.SelectedRegisterId }, null)

    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

InrappAdmin.Web/Views/Leverans/CreateInsamlingsfrekvens.cshtml
@model InrappAdmin.Web.Models.ViewModels.LeveransViewModels.LeveransViewModel

@{
    ViewBag.Title = "Skapa ny insamlingsfrekvens";
}

<script>

    //$(document).ready(function () {
    //    alert("Orgid: " + $('#Organisationsid').val());
    //});
</script>

    @using (Html.BeginForm("CreateInsamlingsfrekvens", "Leverans", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal padding-top-55">
            <h4>Skapa delregister</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })


            <div class="form-group">
                @Html.LabelFor(model => model.Insamlingsfrekvens.Insamlingsfrekvens, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Insamlingsfrekvens.Insamlingsfrekvens, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Insamlingsfrekvens.Insamlingsfrekvens, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Spara" class="btn btn-default" />
                </div>
            </div>
        </div>
        <div>
            @Html.ActionLink("Tillbaka", "GetInsamlingsfrekvens", "Leverans", null, null)

        </div>
    }



    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }