InrappAdmin.Web/Models/ViewModels/OrganisationViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Security.Permissions;
using System.Web;
using InrappAdmin.ApplicationService.DTOModel;
using InrappAdmin.DomainModel;
using Microsoft.AspNet.Identity;

namespace InrappAdmin.Web.Models.ViewModels
{
    public class OrganisationViewModels
    {
        public class OrganisationViewModel
        {
            [Display(Name = "Kommunkod")]
            [StringLength(4, ErrorMessage = "{0} måste vara {2} tecken långt.", MinimumLength = 4)]
            [RegularExpression("([0-9]+)", ErrorMessage = "Kommunkoden måste vara numerisk.")]
            public string Kommunkod { get; set; }
            public Organisation Organisation { get; set; }

            public IEnumerable<ApplicationUserViewModel> ContactPersons { get; set; }

            public string SelectedContactId { get; set; }

            public string SelectedCountyCode { get; set; }
            public int SelectedOrganisationId { get; set; }


            public IEnumerable<Organisationsenhet> OrgUnits { get; set; }

            public  IEnumerable<ReportObligationsViewModel> ReportObligations { get; set; }

        }
        
        public class OrganisationsenhetViewModel
        {
            public int Organisationsid { get; set; }
            public string Enhetsnamn { get; set; }
            public string Enhetskod { get; set; }
            public DateTime? AktivFrom { get; set; }
            public DateTime? AktivTom { get; set; }
            public IEnumerable<UnitReportObligationsViewModel> UnitReportObligations { get; set; }

        }

        public class ReportObligationsViewModel
        {
            public int Id { get; set; }
            public int OrganisationId { get; set; }
            public int DelregisterId { get; set; }
            public string DelregisterKortnamn { get; set; }
            public DateTime? SkyldigFrom { get; set; }
            public DateTime? SkyldigTom { get; set; }
            public bool RapporterarPerEnhet { get; set; }

        }

        public class UnitReportObligationsViewModel
        {
            public int Id { get; set; }
            public int SelectedOrganisationId { get; set; }
            public int SelectedOrganisationsenhetsId { get; set; }
            public int SelectedDelregisterId { get; set; }
            public List<OrganisationDTO> OrganisationList { get; set; }
            public IEnumerable<AdmEnhetsUppgiftsskyldighetViewModel> UnitReportObligations { get; set; }
            public string DelregisterKortnamn { get; set; }
            public string Organisationsnamn { get; set; }
            public int UppgiftsskyldighetId { get; set; }
            public DateTime? SkyldigFrom { get; set; }
            public DateTime? SkyldigTom { get; set; }

        }

        public class AdmEnhetsUppgiftsskyldighetViewModel
        {
            public int Id { get; set; }
            public int OrganisationsenhetsId { get; set; }
            public int UppgiftsskyldighetId { get; set; }
            public DateTime? SkyldigFrom { get; set; }
            public DateTime? SkyldigTom { get; set; }
            public string DelregisterKortnamn { get; set; }
        }


        public class ApplicationUserViewModel
        {
            public string ID { get; set; }
            public int OrganisationId { get; set; }
            public string Namn { get; set; }
            public DateTime? AktivFrom { get; set; }
            public DateTime? AktivTom { get; set; }
            public int? Status { get; set; }
            public string Email { get; set; }
            public string PhoneNumber { get; set; }
            public bool PhoneNumberConfirmed { get; set; }
            public string ValdaDelregister { get; set; }
            public DateTime SkapadDatum { get; set; }
            public string SkapadAv { get; set; }
            public DateTime AndradDatum { get; set; }
            public string AndradAv { get; set; }
            public bool OkToDelete { get; set; }

        }


    }
}

InrappAdmin.Web/Controllers/OrganisationController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using InrappAdmin.ApplicationService;
using InrappAdmin.ApplicationService.DTOModel;
using InrappAdmin.ApplicationService.Interface;
using InrappAdmin.DataAccess;
using InrappAdmin.DomainModel;
using InrappAdmin.Web.Helpers;
using InrappAdmin.Web.Models;
using InrappAdmin.Web.Models.ViewModels;
using Microsoft.AspNet.Identity;

namespace InrappAdmin.Web.Controllers
{
    public class OrganisationController : Controller
    {
        private readonly IPortalAdminService _portalAdminService;


        public OrganisationController()
        {
            _portalAdminService =
                new PortalAdminService(new PortalAdminRepository(new InrappAdminDbContext(), new InrappAdminIdentityDbContext()));
        }

        [Authorize]
        public ActionResult Index()
        {
            // Ladda drop down lists. 
            var orgListDTO = GetOrganisationDTOList();
            ViewBag.OrganisationList = new SelectList(orgListDTO, "Id", "KommunkodOchOrgnamn");
            return View();
        }

        [Authorize]
        // GET: Organisation
        public ActionResult GetOrganisation(OrganisationViewModels.OrganisationViewModel model, int selectedOrganisationId)
        {
            try
            {
                if (selectedOrganisationId != 0)
                {
                    model.SelectedOrganisationId = selectedOrganisationId;
                }
                model.Organisation = _portalAdminService.HamtaOrganisation(model.SelectedOrganisationId);
                model.Kommunkod = model.Organisation.Kommunkod;
                var contacts = _portalAdminService.HamtaKontaktpersonerForOrg(model.Organisation.Id);
                model.ContactPersons = ConvertUsersViewModelUser(contacts);

                model.OrgUnits = _portalAdminService.HamtaOrgEnheterForOrg(model.Organisation.Id);
                var reportObligationsDb = _portalAdminService.HamtaUppgiftsskyldighetForOrg(model.Organisation.Id);
                model.ReportObligations = ConvertAdmUppgiftsskyldighetToViewModel(reportObligationsDb.ToList());
                // Ladda drop down lists. 
                var orgListDTO = GetOrganisationDTOList();
                ViewBag.OrganisationList = new SelectList(orgListDTO, "Id", "KommunkodOchOrgnamn");
                //model.SelectedOrganisationId = 0;
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                ErrorManager.WriteToErrorLog("OrganisationController", "GetOrganisation", e.ToString(), e.HResult, User.Identity.Name);
                var errorModel = new CustomErrorPageModel
                {
                    Information = "Ett fel inträffade vid hämtning av organisation",
                    ContactEmail = ConfigurationManager.AppSettings["ContactEmail"],
                };
                if (e.Message == "Sequence contains no elements")
                {
                    errorModel.Information = "Felaktig kommunkod";
                }

                return View("CustomError", errorModel);

            }
            return View("Index",model);

        }

        // GET
        [Authorize]
        public ActionResult GetContacts()
        {
            // Ladda drop down lists. 
            var orgListDTO = GetOrganisationDTOList();
            ViewBag.OrganisationList = new SelectList(orgListDTO, "Id", "KommunkodOchOrgnamn");

            return View("EditContacts");
        }


        // GET
        [Authorize]
        public ActionResult GetOrganisationsContacts(OrganisationViewModels.OrganisationViewModel model, int selectedOrgId = 0)
        {
            try
            {
                if (selectedOrgId != 0)
                {
                    model.SelectedOrganisationId = selectedOrgId;
                }
                model.Organisation = _portalAdminService.HamtaOrganisation(model.SelectedOrganisationId);
                model.Kommunkod = model.Organisation.Kommunkod;
                var contacts = _portalAdminService.HamtaKontaktpersonerForOrg(model.Organisation.Id);
                model.ContactPersons = ConvertUsersViewModelUser(contacts);
                foreach (var contact in model.ContactPersons)
                {
                    //Hämta användarens valda register
                    contact.ValdaDelregister = GetContactsChosenSubDirectories(contact);
                }
                // Ladda drop down lists. 
                var orgListDTO = GetOrganisationDTOList();
                ViewBag.OrganisationList = new SelectList(orgListDTO, "Id", "KommunkodOchOrgnamn");
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                ErrorManager.WriteToErrorLog("OrganisationController", "GetOrganisationsContacts", e.ToString(), e.HResult,
                    User.Identity.Name);
                var errorModel = new CustomErrorPageModel
                {
                    Information = "Ett fel inträffade vid hämtning av kontakter för organisation.",
                    ContactEmail = ConfigurationManager.AppSettings["ContactEmail"],
                };
                if (e.Message == "Sequence contains no elements")
                {
                    errorModel.Information = "Felaktig kommunkod";
                }
                return View("CustomError", errorModel);
            }
            return View("EditContacts", model);
        }

        //GET
        [Authorize]
        public ActionResult GetOrgUnits()
        {
            // Ladda drop down lists. 
            var orgListDTO = GetOrganisationDTOList();
            ViewBag.OrganisationList = new SelectList(orgListDTO, "Id", "KommunkodOchOrgnamn");
            return View("EditOrgUnits");
        }

        // GET
        [Authorize]
        public ActionResult GetOrganisationsOrgUnits(OrganisationViewModels.OrganisationViewModel model, int selectedOrgId = 0)
        {
            try
            {
                if (selectedOrgId != 0)
                {
                    model.SelectedOrganisationId = selectedOrgId;
                }

                model.Organisation = _portalAdminService.HamtaOrganisation(model.SelectedOrganisationId);
                model.Kommunkod = model.Organisation.Kommunkod;
                model.OrgUnits = _portalAdminService.HamtaOrgEnheterForOrg(model.Organisation.Id);
                // Ladda drop down lists. 
                var orgListDTO = GetOrganisationDTOList();
                ViewBag.OrganisationList = new SelectList(orgListDTO, "Id", "KommunkodOchOrgnamn");

            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                ErrorManager.WriteToErrorLog("OrganisationController", "GetOrganisationsOrgUnits", e.ToString(), e.HResult,
                    User.Identity.Name);
                var errorModel = new CustomErrorPageModel
                {
                    Information = "Ett fel inträffade vid hämtning av organisationsenheter för organisation.",
                    ContactEmail = ConfigurationManager.AppSettings["ContactEmail"],
                };
                if (e.Message == "Sequence contains no elements")
                {
                    errorModel.Information = "Felaktig kommunkod";
                }
                return View("CustomError", errorModel);
            }

            return View("EditOrgUnits", model);
        }

        //GET
        [Authorize]
        public ActionResult GetReportObligations()
        {
            // Ladda drop down lists. 
            var orgListDTO = GetOrganisationDTOList();
            ViewBag.OrganisationList = new SelectList(orgListDTO, "Id", "KommunkodOchOrgnamn");
            return View("EditReportObligations");
        }

        [Authorize]
        public ActionResult GetOrganisationsReportObligations(OrganisationViewModels.OrganisationViewModel model, int selectedOrgId = 0)
        {
            try
            {
                if (selectedOrgId != 0)
                {
                    model.SelectedOrganisationId = selectedOrgId;
                }
                model.Organisation = _portalAdminService.HamtaOrganisation(model.SelectedOrganisationId);
                model.Kommunkod = model.Organisation.Kommunkod;
                var admUppgSkyldighetList = _portalAdminService.HamtaUppgiftsskyldighetForOrg(model.Organisation.Id);
                model.ReportObligations = ConvertAdmUppgiftsskyldighetToViewModel(admUppgSkyldighetList.ToList());
                // Ladda drop down lists. 
                var orgListDTO = GetOrganisationDTOList();
                ViewBag.OrganisationList = new SelectList(orgListDTO, "Id", "KommunkodOchOrgnamn");
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                ErrorManager.WriteToErrorLog("OrganisationController", "GetOrganisationsReportObligations", e.ToString(), e.HResult,
                    User.Identity.Name);
                var errorModel = new CustomErrorPageModel
                {
                    Information = "Ett fel inträffade vid hämtning av uppgiftsskyldighet för organisation.",
                    ContactEmail = ConfigurationManager.AppSettings["ContactEmail"],
                };
                if (e.Message == "Sequence contains no elements")
                {
                    errorModel.Information = "Felaktig kommunkod";
                }
                return View("CustomError", errorModel);
            }

            return View("EditReportObligations", model);
        }

        //GET
        [Authorize]
        public ActionResult GetUnitReportObligations()
        {
            var model = new OrganisationViewModels.UnitReportObligationsViewModel();
            //// Ladda drop down lists. 
            model = GetOrgDropDownLists(model);

InrappAdmin.Web/Views/Organisation/CreateOrganisationUnit.cshtml
@model InrappAdmin.Web.Models.ViewModels.OrganisationViewModels.OrganisationsenhetViewModel

@{
    ViewBag.Title = "Skapa ny organisationsenhet";
}

<script>

    //$(document).ready(function () {
    //    alert("Orgid: " + $('#Organisationsid').val());
    //});
</script>

@using (Html.BeginForm("CreateOrganisationUnit", "Organisation", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(m => m.Organisationsid)

        <div class="form-horizontal padding-top-55">
            <h4>Skapa organisationsenhet</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Organisationsid, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.Organisationsid, htmlAttributes: new { @class = "form-control", disabled = "disabled" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Enhetsnamn, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Enhetsnamn, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Enhetsnamn, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Enhetskod, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Enhetskod, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Enhetskod, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.AktivFrom, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.AktivFrom, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.AktivFrom, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.AktivTom, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.AktivTom, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.AktivTom, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Spara" class="btn btn-default" />
                </div>
            </div>
        </div>
        <div>
            @Html.ActionLink("Tillbaka", "GetOrganisationsOrgUnits", "Organisation", new { selectedOrgId = Model.Organisationsid }, null)

        </div>
    }



    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

InrappAdmin.Web/Views/Organisation/CreateReportObligation.cshtml
@model InrappAdmin.Web.Models.ViewModels.OrganisationViewModels.ReportObligationsViewModel

@{
    ViewBag.Title = "Skapa ny uppgiftsskyldighet";
}

<script>

        //$(document).ready(function () {
        //    alert("Orgid: " + $('#Organisationsid').val());
        //});

    $(document).on('change', '#ddlDelregister', function () {
        $("#DelregisterId").val(parseInt($('#ddlDelregister').val()));
    });

</script>


@using (Html.BeginForm("CreateReportObligation", "Organisation", new { selectedOrgId = Model.OrganisationId }, FormMethod.Post, null))
    {
    @Html.AntiForgeryToken()

    @Html.HiddenFor(m => m.OrganisationId)

    <div class="form-horizontal padding-top-55">
        <h4>Skapa uppgiftsskyldighet</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.OrganisationId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.OrganisationId, htmlAttributes: new { @class = "form-control", disabled = "disabled" })
            </div>
        </div>

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Delregister", new { @class = "control-label col-md-2" })
            <div class="col-md-10" style="width: 225px !important;">
                @Html.DropDownListFor(m => m.DelregisterId, ViewBag.DelregisterList as SelectList, " - Välj delregister -", new { id = "ddlDelregister", @class = "form-control", style = "width:275px !important" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SkyldigFrom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SkyldigFrom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SkyldigFrom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SkyldigTom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SkyldigTom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SkyldigTom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RapporterarPerEnhet, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RapporterarPerEnhet, new { htmlAttributes = new { @class = "checkbox" } })
                @Html.ValidationMessageFor(model => model.RapporterarPerEnhet, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Spara" class="btn btn-default" />
            </div>
        </div>
    </div>
    <div>
        @Html.ActionLink("Tillbaka", "GetOrganisationsReportObligations", "Organisation", new { selectedOrgId = Model.OrganisationId }, null)

    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

InrappAdmin.Web/Views/Organisation/CreateUnitReportObligation.cshtml
@model InrappAdmin.Web.Models.ViewModels.OrganisationViewModels.UnitReportObligationsViewModel

@{
    ViewBag.Title = "Skapa ny enhetsuppgiftsskyldighet för " + Html.Raw(Model.Organisationsnamn);
}

<script>

    $(document).ready(function () {
        var y = $("#SelectedOrganisationsenhetsId").val(); 
        
        if ($("#SelectedOrganisationsenhetsId").val() !== "0") {
            $('#ddlOrgenhet').val($("#SelectedOrganisationsenhetsId").val());
        }
    });

    $(document).on('change', '#ddlOrgenhet', function () {
        $("#SelectedOrganisationsenhetsId").val(parseInt($('#ddlOrgenhet').val()));
    });

        $(document).on('change', '#ddlDelregister', function () {
            $("#SelectedDelregisterId").val(parseInt($('#ddlDelregister').val()));
        });

</script>


@using (Html.BeginForm("CreateUnitReportObligation", "Organisation", FormMethod.Post, null))
    {
    
        @Html.AntiForgeryToken()
        @Html.HiddenFor(m => m.SelectedOrganisationsenhetsId)
        @Html.HiddenFor(m => m.SelectedOrganisationId)

    <div class="form-horizontal padding-top-55">
        <h4>@ViewBag.Title</h4>
        <hr />

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        <div class="form-group">
            @Html.Label("Organisationsenhet", new { @class = "control-label col-md-2" })
            <div class="col-md-10" style="width: 225px !important;">
                @Html.DropDownListFor(m => m.SelectedOrganisationsenhetsId, ViewBag.OrgenhetList as SelectList, " - Välj organisationsenhet -", new { id = "ddlOrgenhet", @class = "form-control", style = "width:275px !important" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Delregister", new { @class = "control-label col-md-2" })
            <div class="col-md-10" style="width: 225px !important;">
                @Html.DropDownListFor(m => m.SelectedDelregisterId, ViewBag.DelregisterList as SelectList, " - Välj delregister -", new { id = "ddlDelregister", @class = "form-control", style = "width:275px !important" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SkyldigFrom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SkyldigFrom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SkyldigFrom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SkyldigTom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SkyldigTom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SkyldigTom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Spara" class="btn btn-default" />
            </div>
        </div>
    </div>
    <div>
        @Html.ActionLink("Tillbaka", "GetOrganisationsUnitReportObligations", "Organisation", new { selectedOrgId = Model.SelectedOrganisationId, selectedOrgenhetsId = Model.SelectedOrganisationsenhetsId }, null)

    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

InrappAdmin.Web/Views/Organisation/_Contactpersons.cshtml
@model InrappAdmin.Web.Models.ViewModels.OrganisationViewModels.OrganisationViewModel

<hr />

<h4>Kontaktpersoner</h4>

<table class="table table-small">
    <tr>
        <th>
            Namn
        </th>
        <th>
            E-postadress
        </th>
        <th>
            Mobilnummer
        </th>
        <th>
            Mobilnummer verifierat
        </th>
        <th>
            Skapad
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.ContactPersons)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Namn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumberConfirmed)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SkapadDatum)
            </td>
        </tr>

    }


</table>

InrappAdmin.Web/Views/Organisation/_OrgUnits.cshtml
@model InrappAdmin.Web.Models.ViewModels.OrganisationViewModels.OrganisationViewModel

<script>
    var x =  @Html.Raw(Model.Organisation.Id);
</script>

<hr />

<h4>Organisationsenheter</h4>

<table class="table table-small">
    <tr>
        <th>
            Enhetsnamn
        </th>
        <th>
            Enhetskod
        </th>
        <th>
            Aktiv från
        </th>
        <th>
            Aktiv tom
        </th>
    </tr>
    @foreach (var item in Model.OrgUnits)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Enhetsnamn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Enhetskod)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AktivFrom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AktivTom)
            </td>

        </tr>
    }


</table>

InrappAdmin.Web/Views/Organisation/_ReportObligations.cshtml
@model InrappAdmin.Web.Models.ViewModels.OrganisationViewModels.OrganisationViewModel

<hr />

<h4>Uppgiftsskyldighet</h4>

<table class="table table-small">
    <tr>
        <th>
            Delregister
        </th>
        <th>
            Skyldig från
        </th>
        <th>
            Skyldig tom
        </th>
        <th>
            Rapportera per enhet
        </th>
    </tr>
    @foreach (var item in Model.ReportObligations)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DelregisterKortnamn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SkyldigFrom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SkyldigTom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RapporterarPerEnhet)
            </td>

            @*<td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                </td>*@
        </tr>
    }


</table>